### ISSUE TITLE
[Question] Form type

### ISSUE THREAD

**Issue by mops1k** [yaroslavche/symfony-ux-flatpickr#1]
Do you plan make form type? Like on dropzone ux?

**Comment by yaroslavche** [comment]
Do you think that's needed? Then I'm ready to help on what I can help =)

**Comment by mops1k** [comment]
Было бы очень удобно иметь такие типы как:
DatePickerType,
DateTimePickerType,
DatePickerRangeType,
DateTimePickerRangeType,
TimePickerType,
TimePickerRangeType

Я бы с удовольствие сделал сам, но я совершенно не разбираюсь в symfony-ux и самом flatpickr :)
Просто сам выбор как это сделано сейчас без формы, мало актуален в symfony среде, потому что по большей части везде используются Symfony Forms. Взять те же генераторы админок - Sonata Admin Bundle, Easy Admin Bundle. Всё крутиться в формах и вот тут такой компонент реально хорошо зашёл бы и сохранил бы кучу времени людям.
Я не знаю с чего начать с ux, чтобы ваш труд немного перелопатить под типы форм, но готов обсудить и попробовать как-то совместно решить вопрос. :)

**Comment by yaroslavche** [comment]
Ну по сути, Вы говорите всё правильно - нужно создать типы форм (базовую и расширения для подтипов) и просто их использовать. Сейчас сложно сказать как именно будет выглядеть, но я попробую что-то слдделать, когда будет время (обещать не могу =))

**Comment by yaroslavche** [comment]
~мне кажется, я что-то поломал при инициализации контроллера stimulus и оно не работает. Буду позже разбираться.
Но в целом оно работало.~ (исправил для stimulus-bridge 2.0)
У меня остались вопросы:
 - нужно ли все эти типы Date, DateTime, etc, или может лучше конфиг передавать прямо при добавлении в форму поля (одного типа формы Flatpickr)?
 - нужен ли вообще flatpickr instance, если оно хорошо работает просто передав конфиг через `data-config`?
 - ну и рэнжи я не пробовал, вроде как раз для этого нужен инстанс.
~Впрочем, пока рано это обсуждать, сначала нужно исправить контроллер)~
